server:
  port: ${PORT:9001}

spring:
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      exclude: 'static/**,public/**'
  security:
    user:
      roles: ${CONFIG_ROLES:manager}
      name: ${CONFIG_USERNAME:adminz}
      password: ${CONFIG_PASSWORD:123123zZ}
  application:
    name: CONFIG-SERVER

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
