server:
  port: ${PORT:9001}

spring:
  application:
    name: CONFIG-SERVER
  security:
    user:
      roles: ${CONFIG_ROLES:manager}
      name: ${CONFIG_USERNAME:adminz}
      password: ${CONFIG_PASSWORD:123123zZ}
  cloud:
    config:
      server:
        bootstrap: true
        health:
          enabled: false
        native:
          addLabelLocations: false
          searchLocations: classpath:/config
        git:
          uri: https://github.com/ravuthz/config-store
          force-pull: true
          clone-on-start: true
          username: ravuthz
          password: 1234@Abz$
          default-label: master
#  devtools:
#    add-properties: false
#    livereload:
#      enabled: false
#    restart:
#      exclude: 'static/**,public/**'
eureka:
  instance:
    hostname: localhost
  client:
    register-with-euraka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://${SECURITY_USERNAME:adminz}:${SECURITY_PASSWORD:123123zZ}@${eureka.instance.hostname}:8761/eureka/}
logging:
  level:
    root: INFO
    org:
      apache:
        catalina: DEBUG
      springframework:
        boot:
          env: DEBUG
        core:
          env: DEBUG
---
spring:
  profiles:
    active: dev
logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){highlight} %highlight(%-5level) - %msg%n'
  level:
    root: INFO
    io:
      microservice:
        server: DEBUG
        service: DEBUG
    org:
      apache:
        catalina: DEBUG
    com:
      zaxxer: DEBUG
